version: '3.7'

networks:
  main:

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - main

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=trello
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - main

  auth:
    container_name: 'auth'
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - main

  main:
    container_name: 'main'
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - main

volumes:
  pgdata:
  rabbitmq_data: